# -*- coding: utf-8 -*-
"""Q3 part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

# 1. Install necessary library
!pip install scikit-fuzzy
import numpy as np
import cv2
import matplotlib.pyplot as plt
import skfuzzy as fuzz

# --- Step 1: Load or Generate Image ---
# Aap apni image load karne ke liye niche wali line uncomment kar sakte hain:
# img = cv2.imread('your_image.jpg', cv2.IMREAD_GRAYSCALE)

# Agar 'img' variable abhi tak define nahi hua hai (yaani image load nahi hui),
# toh hum ek simple gradient image banayenge taake code error na de.
if 'img' not in locals():
    img = np.zeros((100, 100), dtype=np.uint8)
    img[0:50, :] = 50  # Dark region
    img[50:80, :] = 150 # Gray region
    img[80:100, :] = 250 # White region

# --- Step 2: Pre-processing (1D Conversion) ---
# Image ko 1D array mein badalna zaroori hai
pixels = img.reshape(-1, 1).astype(float)

# --- Step 3: Apply Fuzzy C-Means (c=3) ---
# skfuzzy expects data in (features, samples) format, so we use .T
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    pixels.T, c=3, m=2, error=0.005, maxiter=1000)

# --- Step 4: Reconstruct Image ---
# Har pixel ko us cluster ka center dena jiski membership sab se zyada hai
cluster_membership = np.argmax(u, axis=0)
segmented_pixels = cntr[cluster_membership]

# Reshape back to original 2D image shape
segmented_img = segmented_pixels.reshape(img.shape)

# --- Step 5: Display Results ---
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Grayscale Image")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(segmented_img, cmap='gray')
plt.title(f"FCM Segmented (Clusters=3, FPC={fpc:.2f})")
plt.axis('off')
plt.show()