# -*- coding: utf-8 -*-
"""Q4 part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import numpy as np
import pandas as pd
import skfuzzy as fuzz
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
# 1. Create Dataset (15 Customers)
data = {
 'Age': [25, 45, 30, 35, 22, 48, 50, 21, 55, 60, 28, 40, 33, 42, 23],
 'Income': [30, 80, 40, 100, 25, 90, 110, 35, 120, 50, 45, 95, 70, 85, 30],
 'Spending_Score': [80, 20, 70, 90, 75, 15, 10, 85, 25, 30, 60, 95, 50, 10, 90]}
df = pd.DataFrame(data)
# 2. Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(df)
# 3. Apply FCM
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
 X_scaled.T, c=3, m=2, error=0.005, maxiter=1000)
# 4. Membership & Cluster Assignment
df['Cluster'] = np.argmax(u, axis=0)
membership_matrix = pd.DataFrame(u.T, columns=['C1_Prob', 'C2_Prob', 'C3_Prob'])
print("Cluster Centers (Normalized):\n", cntr)
print("\nFirst 5 Membership Values:\n", membership_matrix.head())
