# -*- coding: utf-8 -*-
"""Q 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
import skfuzzy as fuzz
from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans
# Load Dataset
iris = load_iris()
X, y = iris.data, iris.target
# Normalize (Range 0-1)
X_scaled = MinMaxScaler().fit_transform(X)
# Apply FCM (c=3 clusters, m=2 fuzziness)
# We transpose X_scaled to (features, samples) for skfuzzy
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    X_scaled.T, c=3, m=2, error=0.005, maxiter=1000)
# Get Predicted Labels
fcm_labels = np.argmax(u, axis=0)
def map_labels(predicted, actual):
    mapped = np.zeros_like(predicted)
    for i in range(3):
        mask = (predicted == i)
        if np.any(mask):
            mapped[mask] = np.bincount(actual[mask]).argmax()
    return mapped
fcm_mapped = map_labels(fcm_labels, y)
# Display First 20
comparison = pd.DataFrame({'Actual': y[:20], 'FCM_Predicted': fcm_mapped[:20]})
print(comparison)