# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

# Install the scikit-fuzzy library
!pip install scikit-fuzzy
import numpy as np
import matplotlib.pyplot as plt
import skfuzzy as fuzz
# --- Step 1: Generate Synthetic 2D Dataset ---
np.random.seed(42) # For reproducibility
# Define 3 cluster centers in a 2D plane
centers = [[2, 2], [5, 5], [8, 2]]
# Generate points using Gaussian noise (100 points per cluster)
cluster1 = np.random.randn(100, 2) * 0.5 + centers[0]
cluster2 = np.random.randn(100, 2) * 0.6 + centers[1]
cluster3 = np.random.randn(100, 2) * 0.5 + centers[2]
# Combine all clusters into a single dataset
data = np.vstack([cluster1, cluster2, cluster3])
# --- Step 2: Apply Fuzzy C-Means (FCM) Clustering ---
# We transpose 'data' because skfuzzy expects features in rows (2, 300)
# c=3 (number of clusters), m=2 (degree of fuzziness)
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    data.T, c=3, m=2, error=0.005, maxiter=1000, init=None
)
# --- Step 3: Analyze Results ---
# Get the cluster with the highest membership value for each point
cluster_membership = np.argmax(u, axis=0)
# --- Step 4: Visualization ---
plt.figure(figsize=(8, 6))
# Plot each cluster with a different color
colors = ['blue', 'green', 'red']
for j in range(3):
    plt.scatter(data[cluster_membership == j, 0],
                data[cluster_membership == j, 1],
                c=colors[j], label=f'Cluster {j+1}', alpha=0.6)
# Mark the calculated cluster centers
plt.scatter(cntr[:, 0], cntr[:, 1], marker='X', s=200,
            color='yellow', edgecolor='black', label='Calculated Centers')
plt.title(f"Fuzzy C-Means Result (FPC: {fpc:.2f})")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.legend()
plt.grid(True)
plt.show()