# -*- coding: utf-8 -*-
"""Task 14(task6).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import gymnasium as gym
import cv2
import numpy as np
from IPython.display import Image, display
#Task: Setup CartPole-v1
env=gym.make('CartPole-v1',render_mode='rgb_array')
cp_scores=[]
frames=[]
print("Running CartPole-v1 for 50 Episodes...")
for episode in range(1,51):
    state,info=env.reset()
    total_reward=0
    terminated=False
    truncated=False
    while not(terminated or truncated):
        #Task 2 Identify: [Cart Pos, Cart Vel, Pole Angle, Pole Ang Vel]
        action=env.action_space.sample()
        state,reward,terminated,truncated,info=env.step(action)
        total_reward+=reward
        if episode==1:
            frame=env.render()
            frame=cv2.cvtColor(frame,cv2.COLOR_RGB2BGR)
            #Task 3: Blue score at (200, 20)
            cv2.putText(frame,f"Score: {int(total_reward)}",(200,20),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,0,0),2)
            frames.append(frame)
    cp_scores.append(total_reward)
env.close()
print(f"CartPole Best Score: {max(cp_scores)}")
cv2.imwrite('cartpole_result.png',frames[10] if len(frames)>10 else frames[0])
display(Image('cartpole_result.png'))