# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

!pip install gymnasium
!pip install matplotlib


import gymnasium as gym
import matplotlib.pyplot as plt


env = gym.make("CartPole-v1", render_mode="rgb_array")


num_episodes = 50
scores = []


for episode in range(1, num_episodes + 1):
    score = 0
    state, info = env.reset()
    done = False


    while not done:
        action = env.action_space.sample()
        state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        score += reward


    scores.append(score)

    print(f"Episode: {episode} | Score: {score}")




plt.figure(figsize=(12,6))
plt.plot(range(1, num_episodes+1), scores, marker='o')
plt.title("Episode vs Score (Random Agent)")
plt.xlabel("Episode")
plt.ylabel("Score")
plt.grid(True)
plt.show()


env.close()
