# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

!pip install gymnasium
import gymnasium as gym
import numpy as np
env = gym.make("CartPole-v1", render_mode="rgb_array")
num_episodes = 50
scores = []
for episode in range(1, num_episodes + 1):
    score = 0
    state, info = env.reset()
    done = False

    while not done:
        action = env.action_space.sample()
        state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        score += reward
    scores.append(score)
    print(f"Episode {episode} Score: {score}")

average_score = np.mean(scores)
print(f"\nAverage Score over {num_episodes} episodes: {average_score:.2f}")
