# -*- coding: utf-8 -*-
"""Task 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import gymnasium as gym
import numpy as np
env = gym.make('MountainCar-v0')
scores = []
# Task: Changed range from 20 to 50
for episode in range(1, 51):
    state, info = env.reset()
    done = False
    truncated = False
    total_reward = 0
    while not (done or truncated):
        # Using a simple heuristic: push in the direction of velocity
        # This is more interesting than random sampling
        velocity = state[1]
        action = 2 if velocity > 0 else 0
        state, reward, done, truncated, info = env.step(action)
        total_reward += reward
    scores.append(total_reward)
    print(f"Episode: {episode} | Score: {total_reward}")
env.close()
# Average score across 50 episodes
print(f"\nAverage Score: {np.mean(scores)}")
