# -*- coding: utf-8 -*-
"""Q3 part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import skfuzzy as fuzz
# 1. Load a grayscale image
image = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE)
if image is None:
    # If loading fails, create a simple gradient for testing
    image = np.linspace(0, 255, 10000).reshape(100, 100).astype(np.uint8)
# 2. Convert image into a 1D pixel array
pixels = image.reshape(-1, 1).astype(float)
# 3. Apply Fuzzy C-Means (c=3 clusters)
# We transpose 'pixels' because skfuzzy expects (features, samples)
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    pixels.T, c=3, m=2, error=0.005, maxiter=1000)
# 4. Reconstruct the segmented image
# Assign each pixel to the cluster center with the highest membership
cluster_membership = np.argmax(u, axis=0)
segmented_pixels = cntr[cluster_membership]
segmented_image = segmented_pixels.reshape(image.shape) # Display Results
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1); plt.imshow(image, cmap='gray'); plt.title("Original")
plt.subplot(1, 2, 2); plt.imshow(segmented_image, cmap='gray'); plt.title("FCM Segmented (c=3)")
plt.show()