# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import pandas as pd
import numpy as np
import skfuzzy as fuzz
from sklearn.preprocessing import StandardScaler

# Filtering the selected countries
countries = ['Pakistan', 'India', 'China', 'Iran',
'Afghanistan']

# --- FIX: Create a dummy DataFrame as the CSV file was not found ---
# In a real scenario, you would ensure 'covid_world_dataset.csv' is in the correct path
# or provide the correct path to pd.read_csv()
# For demonstration, we'll create a DataFrame that mimics the expected structure.
data = {
    'Country': ['Pakistan', 'India', 'China', 'Iran', 'Afghanistan', 'USA', 'Germany', 'Brazil', 'Canada', 'Mexico'],
    'Total Cases': [500000, 30000000, 1000000, 7000000, 150000, 90000000, 30000000, 35000000, 15000000, 7000000],
    'Total Deaths': [10000, 400000, 5000, 150000, 7000, 1000000, 150000, 500000, 50000, 300000],
    'Total Recovered': [480000, 29000000, 950000, 6500000, 140000, 80000000, 28000000, 32000000, 14000000, 6500000],
    'Population': [220000000, 1380000000, 1440000000, 83000000, 38000000, 330000000, 83000000, 212000000, 38000000, 128000000]
}
df = pd.DataFrame(data)

# Filtering for specific countries and columns as per the original intent
target_countries = ['Pakistan', 'India', 'China', 'Iran', 'Afghanistan']
df_filtered = df[df['Country'].isin(target_countries)].copy()

# Features: Total Cases, Total Deaths, Total Recovered
# Ensure these columns exist in df_filtered
features = df_filtered[['Total Cases', 'Total Deaths', 'Total Recovered']].values

# Normalizing data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

# Selecting the required variables for analysis_data
analysis_data = df_filtered[['Country', 'Total Cases', 'Total Deaths', 'Population']]

print("DataFrame 'df' created successfully.")
print("DataFrame 'df_filtered' created for target countries.")
print("X_scaled (normalized features) created.")
print("Analysis data for target countries created.")
display(analysis_data.head())