# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import matplotlib.pyplot as plt
import numpy as np # Import numpy for data generation

# --- Placeholder Data (normally these would be outputs from a clustering algorithm) ---
# For demonstration, creating some sample data that might be clustered.
np.random.seed(0)
n_samples = 150
# Generate 3 blobs of data
data1 = np.random.rand(50, 2) * 2 + [1, 1]
data2 = np.random.rand(50, 2) * 2 + [5, 5]
data3 = np.random.rand(50, 2) * 2 + [1, 5]
data = np.vstack((data1, data2, data3))

# Dummy cluster_membership and cntr (cluster centers) for the placeholder data.
# In a real scenario, these would come from the fuzzy C-means algorithm's output.
cluster_membership = np.zeros(n_samples, dtype=int)
cluster_membership[0:50] = 0
cluster_membership[50:100] = 1
cluster_membership[100:150] = 2

cntr = np.array([
    [2, 2], # Center for cluster 0
    [6, 6], # Center for cluster 1
    [2, 6]  # Center for cluster 2
])
# --- End of Placeholder Data ---


# 1. Initialize the plot figure size
plt.figure(figsize=(10, 7))
# 2. Define colors for our 3 clusters
colors = ['#3498db', '#2ecc71', '#e74c3c'] # Blue, Green, Red
# 3. Loop through each cluster to plot points
for j in range(3):
 # Select points belonging to the current cluster
  cluster_points = data[cluster_membership == j]
  plt.scatter(cluster_points[:, 0], cluster_points[:, 1],
  c=colors[j], label=f'Cluster {j+1}',
  alpha=0.5, edgecolors='none', s=30)
# 4. Plot the Cluster Centers (Centroids)
# These were returned as 'cntr' by the fuzz.cluster.cmeans function
plt.scatter(cntr[:, 0], cntr[:, 1], marker='X', s=250,
  color='yellow', edgecolor='black', linewidth=1.5,
  label='Cluster Centers')
# 5. Add Plot Details
plt.title("Fuzzy C-Means: Clustered Data Points and Centers", fontsize=14)
plt.xlabel("X-Axis (Feature 1)")
plt.ylabel("Y-Axis (Feature 2)")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()