# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import numpy as np
import matplotlib.pyplot as plt
# 1. Random seed setting
np.random.seed(42)
# 2. Teen clusters centers
# Cluster 1: (2, 2), Cluster 2: (5, 5), Cluster 3: (8, 2)
centers = [[2, 2], [5, 5], [8, 2]]
# 3. Gaussian noise points generation
cluster1 = np.random.randn(100, 2) + centers[0]
cluster2 = np.random.randn(100, 2) + centers[1]
cluster3 = np.random.randn(100, 2) + centers[2]
# 4. Combine all Tamam clusters in one datasheet
data = np.vstack([cluster1, cluster2, cluster3])
# Visualization
plt.scatter(data[:, 0], data[:, 1], s=10, color='gray')
plt.title("Synthetic 2D Dataset with 3 Clusters")
plt.show()