# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import pandas as pd
import numpy as np

# Assuming 'data' and 'u' are defined from a previous fuzzy c-means clustering step.
# For demonstration purposes, I'll create placeholder 'data' and 'u' if they don't exist.
# In a real scenario, 'u' would be the membership matrix from fuzz.cluster.cmeans().

if 'data' not in globals() or not isinstance(data, np.ndarray):
    # Create some dummy data if 'data' is not defined
    np.random.seed(42)
    data1 = np.random.rand(50, 2) * 2 + [1, 1]
    data2 = np.random.rand(50, 2) * 2 + [5, 5]
    data3 = np.random.rand(50, 2) * 2 + [1, 5]
    data = np.vstack((data1, data2, data3))

if 'u' not in globals() or not isinstance(u, np.ndarray):
    # Create a dummy membership matrix 'u' if not defined
    # This assumes 3 clusters for the dummy 'data'
    u = np.zeros((3, len(data)))
    for i in range(len(data)):
        if i < 50:
            u[0, i] = 0.8
            u[1, i] = 0.1
            u[2, i] = 0.1
        elif i < 100:
            u[0, i] = 0.1
            u[1, i] = 0.8
            u[2, i] = 0.1
        else:
            u[0, i] = 0.1
            u[1, i] = 0.1
            u[2, i] = 0.8
    # Normalize so each column sums to 1 (membership for each point)
    u = u / u.sum(axis=0)


# 1. Select 5 random indices from the dataset
random_indices = np.random.choice(range(len(data)), size=5, replace=False)

# 2. Extract membership values for these specific points
# We take the transpose of 'u' to align it with our points
selected_membership = u.T[random_indices]

# 3. Create a clean table (DataFrame) for display
membership_df = pd.DataFrame(
    selected_membership,
    columns=['Cluster 1 Membership', 'Cluster 2 Membership', 'Cluster 3 Membership'],
    index=[f"Point {i}" for i in random_indices])

# 4. Display the results
print("Membership Values for 5 Random Points:")
print("-" * 50)
print(membership_df.round(4)) # Rounding to 4 decimal places for clarity
print("-" * 50)

# Optional: Verify that the sum of memberships for each point equals 1
print("\nSum of memberships for each point (Should be 1.0):")
print(membership_df.sum(axis=1))