# -*- coding: utf-8 -*-
"""Task 11(task3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

!pip install gymnasium[classic_control]

import gymnasium as gym
import cv2
import numpy as np
from IPython.display import Image, display
# 1. Setup Environment
env = gym.make('MountainCar-v0', render_mode='rgb_array')
frames = []
print("Starting 50 Episodes...")
# Task 1: Run 50 episodes
for episode in range(1, 51):
    state, info = env.reset()
    total_reward = 0
    terminated = False
    truncated = False


    while not (terminated or truncated):
        # Task 2: Identify Position and Velocity
        pos, vel = state[0], state[1]

        # We only print the first few steps of Episode 1 to avoid crashing Colab's output
        if episode == 1 and total_reward > -5:
            print(f"Ep {episode} | Position: {pos:.4f} | Velocity: {vel:.4f}")


        # Action: Random sampling
        action = env.action_space.sample()
        state, reward, terminated, truncated, info = env.step(action)
        total_reward += reward


        # --- Task 3: Drawing the UI ---
        # Only capture frames for the first episode to show as an example
        if episode == 1:
            frame = env.render()
            frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

            # Change color to BLUE (255, 0, 0) and Position to (200, 20)
            cv2.putText(frame, f"Score: {int(total_reward)}", (200, 20),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            frames.append(frame)
    if episode % 10 == 0:
        print(f"Episode {episode} completed.")
env.close()
# Save the first episode as a GIF to view in Colab
out = cv2.VideoWriter('mountain_car.png', cv2.VideoWriter_fourcc(*'png '), 30, (600, 400))
# Using a simpler display method for Colab: Save one frame as a preview
cv2.imwrite('result_preview.png', frames[50])
print("\nSimulation Finished. Showing a preview frame from Episode 1:")
display(Image('result_preview.png'))