# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

!pip install gymnasium

import gymnasium as gym

env = gym.make("MountainCar-v0", render_mode="rgb_array")

state, info = env.reset()

print("Initial State Vector:", state)
print("Number of State Variables:", len(state))

env.close()