# -*- coding: utf-8 -*-
"""Task 16(task8).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import gymnasium as gym
import numpy as np
env=gym.make('MountainCar-v0',render_mode='rgb_array')
step_counts=[]
all_scores=[]
print("Analyzing 50 Episodes...")
for episode in range(1,51):
    state,info=env.reset()
    steps=0
    total_reward=0
    terminated=False
    truncated=False
    while not(terminated or truncated):
        # Using Rule-Based Policy from Task 7 for success data
        action=2 if state[1]>0 else 0
        state,reward,terminated,truncated,info=env.step(action)
        total_reward+=reward
        steps+=1
    step_counts.append(steps)
    all_scores.append(total_reward)
    print(f"Ep {episode}: Steps={steps} | Score={total_reward}")
env.close()
print(f"\nMax Steps: {max(step_counts)} | Min Steps: {min(step_counts)}")