# -*- coding: utf-8 -*-
"""Task 12(task4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import gymnasium as gym
import cv2
import numpy as np
from IPython.display import Image, display
# 1. Setup Environment
env = gym.make('MountainCar-v0', render_mode='rgb_array')
# Task 4 Initialization: Store scores
all_scores = []
best_frame = None
print("Starting 50 Episodes...")
for episode in range(1, 51):
    state, info = env.reset()
    total_reward = 0
    terminated = False
    truncated = False
    while not (terminated or truncated):
        # Task 2: State Identification
        pos, vel = state[0], state[1]
        # Action: Random sampling
        action = env.action_space.sample()
        state, reward, terminated, truncated, info = env.step(action)
        total_reward += reward
        # Capture a frame for visualization (Optional preview)
        if episode == 1 and len(all_scores) == 0:
            frame = env.render()
            frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
            cv2.putText(frame, f"Score: {int(total_reward)}", (200, 20),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            best_frame = frame
    # Task 4: Store score after each episode
    all_scores.append(total_reward)
    if episode % 10 == 0:
        print(f"Episode {episode}/50 - Current Score: {total_reward}")
env.close()
# Task 4: Print the Best Performance
best_score = max(all_scores)
print("\n" + "="*30)
print(f"SIMULATION COMPLETE")
print(f"Best Score (Highest): {best_score}")
print(f"Average Score: {np.mean(all_scores):.2f}")
print("="*30)
# Show preview
cv2.imwrite('best_performance.png', best_frame)
display(Image('best_performance.png'))