# -*- coding: utf-8 -*-
"""Task 15(task7).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import gymnasium as gym
import cv2
import numpy as np
from IPython.display import Image, display
env=gym.make('MountainCar-v0',render_mode='rgb_array')
scores=[]
frames=[]
print("Running Rule-Based Policy...")
for episode in range(1,11): #Running 10 episodes to observe success
    state,info=env.reset()
    total_reward=0
    terminated=False
    truncated=False
    while not(terminated or truncated):
        #Task 7: Rule-Based Policy
        #state[1] is Velocity
        if state[1]>0:
            action=2
        else:
            action=0
        state,reward,terminated,truncated,info=env.step(action)
        total_reward+=reward
        if episode==1:
            frame=env.render()
            frame=cv2.cvtColor(frame,cv2.COLOR_RGB2BGR)
            cv2.putText(frame,f"Score: {int(total_reward)}",(200,20),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,0,0),2)
            frames.append(frame)
    scores.append(total_reward)
    print(f"Episode {episode} Score: {total_reward} | {'SUCCESS' if terminated else 'FAILED'}")
env.close()
print(f"Best Score with Policy: {max(scores)}")
#Save success frame
if frames:
    cv2.imwrite('success_preview.png',frames[-1])
    display(Image('success_preview.png'))