# -*- coding: utf-8 -*-
"""Task 13(task5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EedVXDR_fZj1UaX-OYpw1AcBEiwOPgC9
"""

import gymnasium as gym
import cv2
import numpy as np
import time
from IPython.display import Image, display
#Task: Setup environment for Colab
env=gym.make('MountainCar-v0',render_mode='rgb_array')
all_scores=[]
frames=[]
print("Simulation Start: Running 50 Episodes...")
for episode in range(1,51):
    state,info=env.reset()
    total_reward=0
    terminated=False
    truncated=False
    while not(terminated or truncated):
        #Task 2: Identify Position and Velocity
        pos,vel=state[0],state[1]
        #Action: Random sampling
        action=env.action_space.sample()
        state,reward,terminated,truncated,info=env.step(action)
        total_reward+=reward
        #Task 5: Slow down (Simulated delay)
        time.sleep(0.01)
        #Task 3: Blue Score (200, 20) - Capture Episode 1 frames
        if episode==1:
            frame=env.render()
            frame=cv2.cvtColor(frame,cv2.COLOR_RGB2BGR)
            cv2.putText(frame,f"Score: {int(total_reward)}",(200,20),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,0,0),2)
            frames.append(frame)
    all_scores.append(total_reward)
    if episode%10==0:
        print(f"Episode {episode} Finished. State -> Pos: {pos:.2f}, Vel: {vel:.4f}")
env.close()
#Task 4: Best Performance
print("\n"+"="*20)
print(f"Best Score: {max(all_scores)}")
print(f"Average Score: {np.mean(all_scores)}")
print("="*20)
#Display result
cv2.imwrite('result.png',frames[100])
print("\nPreview of Episode 1 (Blue Score at 200,20):")
display(Image('result.png'))